// GERADO POR tool/build_curriculum_outline.py — NÃO EDITE À MÃO.
//
// Esqueleto das trilhas do app: o servidor usa isto para saber até
// onde a pessoa chegou e para montar o prompt do desafio do dia só
// com assunto que ela já viu. O conteúdo das lições continua só no
// app; aqui ficam id e título.
//
// Regenere depois de mexer em qualquer trilha.

export interface OutlineLesson {
  id: string;
  title: string;
}

export interface OutlineLevel {
  languageId: string;
  /** Posição do nível dentro da trilha da própria linguagem. */
  index: number;
  title: string;
  description: string;
  lessons: OutlineLesson[];
}

export const CURRICULUM_OUTLINE: OutlineLevel[] = [
  {"languageId": "logic", "index": 0, "title": "Fundamentos: jogos de lógica", "description": "Enigmas, sequências e escolhas antes das linguagens", "lessons": [{"id": "logic1_0", "title": "Missão: detetive da lógica"}, {"id": "logic1_1", "title": "Labirinto das setas"}, {"id": "logic1_2", "title": "Sequência das gemas"}, {"id": "logic1_3", "title": "Duelo de pontuação"}, {"id": "logic1_4", "title": "Regra secreta do castelo"}, {"id": "logic1_5", "title": "Guardião das duas chaves"}, {"id": "logic1_6", "title": "Baús mentirosos"}, {"id": "logic1_7", "title": "Mapa da fase"}]},
  {"languageId": "logic", "index": 1, "title": "Fundamentos: enigmas e estratégia", "description": "Memória, dedução, prioridades e desafios em camadas", "lessons": [{"id": "logic2_0", "title": "Sala dos padrões"}, {"id": "logic2_1", "title": "Senha colorida"}, {"id": "logic2_2", "title": "Torre dos pesos"}, {"id": "logic2_3", "title": "Ilha das escolhas"}, {"id": "logic2_4", "title": "Elimine impossíveis"}, {"id": "logic2_5", "title": "Quem está no meio?"}, {"id": "logic2_6", "title": "Memória das cartas"}, {"id": "logic2_7", "title": "Desafio final: portal das linguagens"}]},
  {"languageId": "python", "index": 0, "title": "Python Essencial", "description": "Sintaxe, variáveis, textos e cálculos", "lessons": [{"id": "py_basic_0", "title": "O Python fala com print"}, {"id": "py_basic_1", "title": "Use print()"}, {"id": "py_basic_2", "title": "Variáveis no código"}, {"id": "py_basic_3", "title": "Crie e use uma variável"}, {"id": "py_basic_4", "title": "Números e operadores"}, {"id": "py_basic_5", "title": "Calcule um total"}, {"id": "py_basic_6", "title": "Textos também somam"}, {"id": "py_basic_7", "title": "Leia o erro antes de tentar de novo"}]},
  {"languageId": "python", "index": 1, "title": "Funções em Python", "description": "Crie comandos reutilizáveis e claros", "lessons": [{"id": "func_0", "title": "Por que criar funções?"}, {"id": "func_1", "title": "Crie uma função simples"}, {"id": "func_2", "title": "Parâmetros"}, {"id": "func_3", "title": "Função com parâmetro"}, {"id": "func_4", "title": "Mais de um parâmetro"}, {"id": "func_5", "title": "Cálculo dentro da função"}, {"id": "func_6", "title": "Função com decisão"}, {"id": "func_7", "title": "Valide uma nota"}, {"id": "func_8", "title": "Reutilização real"}, {"id": "func_9", "title": "Funções pequenas vencem"}]},
  {"languageId": "python", "index": 2, "title": "Fluxos reais com Python", "description": "Regras, classificações e validações", "lessons": [{"id": "flow_0", "title": "if, elif e else"}, {"id": "flow_1", "title": "Classifique pontos"}, {"id": "flow_2", "title": "Desconto por regra"}, {"id": "flow_3", "title": "Rastreamento de código"}, {"id": "flow_4", "title": "Loop com acumulador real"}, {"id": "flow_5", "title": "Regra dentro de função"}]},
  {"languageId": "python", "index": 3, "title": "Mini projetos guiados", "description": "Junte lógica, Python e funções", "lessons": [{"id": "proj_0", "title": "Projeto: calculadora de compra"}, {"id": "proj_1", "title": "Monte a compra"}, {"id": "proj_2", "title": "Projeto: jogo de adivinhação"}, {"id": "proj_3", "title": "Complete o jogo"}, {"id": "proj_4", "title": "Projeto: rotina de estudos"}, {"id": "proj_5", "title": "Próximo passo"}]},
  {"languageId": "javascript", "index": 0, "title": "JavaScript: primeiros passos", "description": "A linguagem que roda dentro de todo navegador", "lessons": [{"id": "js_basic_0", "title": "Onde o JavaScript vive"}, {"id": "js_basic_1", "title": "Mostrando na tela"}, {"id": "js_basic_2", "title": "Guardando um valor"}, {"id": "js_basic_3", "title": "let, const ou var"}, {"id": "js_basic_4", "title": "Decidindo com if"}, {"id": "js_basic_5", "title": "Comparação que não engana"}]},
  {"languageId": "javascript", "index": 1, "title": "JavaScript na prática", "description": "Repetição, funções e listas", "lessons": [{"id": "js_pratica_0", "title": "Repetindo sem copiar e colar"}, {"id": "js_pratica_1", "title": "Contando de 1 a 3"}, {"id": "js_pratica_2", "title": "Empacotando em função"}, {"id": "js_pratica_3", "title": "Devolvendo um resultado"}, {"id": "js_pratica_4", "title": "Listas que crescem"}, {"id": "js_pratica_5", "title": "Para onde ir agora"}]},
  {"languageId": "typescript", "index": 0, "title": "TypeScript: primeiros passos", "description": "JavaScript que avisa o erro antes de rodar", "lessons": [{"id": "ts_basic_0", "title": "Por que existe TypeScript"}, {"id": "ts_basic_1", "title": "Anotando o tipo"}, {"id": "ts_basic_2", "title": "Função com tipos"}, {"id": "ts_basic_3", "title": "Os três tipos do dia a dia"}, {"id": "ts_basic_4", "title": "Desenhando um objeto"}, {"id": "ts_basic_5", "title": "Lista com tipo"}]},
  {"languageId": "typescript", "index": 1, "title": "TypeScript na prática", "description": "Nulos, uniões e código que não quebra", "lessons": [{"id": "ts_pratica_0", "title": "Pode ser nulo"}, {"id": "ts_pratica_1", "title": "Parâmetro opcional"}, {"id": "ts_pratica_2", "title": "Um valor entre poucos"}, {"id": "ts_pratica_3", "title": "Só leitura"}, {"id": "ts_pratica_4", "title": "O tipo que desliga tudo"}, {"id": "ts_pratica_5", "title": "Para onde ir agora"}]},
  {"languageId": "java", "index": 0, "title": "Java: primeiros passos", "description": "A linguagem por trás de bancos e do Android", "lessons": [{"id": "java_basic_0", "title": "Onde o Java está"}, {"id": "java_basic_1", "title": "Escrevendo na tela"}, {"id": "java_basic_2", "title": "Variável com tipo"}, {"id": "java_basic_3", "title": "Texto é objeto"}, {"id": "java_basic_4", "title": "Decidindo com if"}, {"id": "java_basic_5", "title": "Comparando textos"}]},
  {"languageId": "java", "index": 1, "title": "Java na prática", "description": "Laços, métodos e listas", "lessons": [{"id": "java_pratica_0", "title": "Repetindo item a item"}, {"id": "java_pratica_1", "title": "Contando de 1 a 3"}, {"id": "java_pratica_2", "title": "Método que devolve"}, {"id": "java_pratica_3", "title": "Lista que cresce"}, {"id": "java_pratica_4", "title": "Molde e objeto"}, {"id": "java_pratica_5", "title": "Para onde ir agora"}]},
  {"languageId": "csharp", "index": 0, "title": "C#: primeiros passos", "description": "A linguagem do .NET e do Unity", "lessons": [{"id": "cs_basic_0", "title": "Onde o C# está"}, {"id": "cs_basic_1", "title": "Escrevendo na tela"}, {"id": "cs_basic_2", "title": "Variável com tipo"}, {"id": "cs_basic_3", "title": "Deixando o compilador deduzir"}, {"id": "cs_basic_4", "title": "Decidindo com if"}, {"id": "cs_basic_5", "title": "Texto com valor dentro"}]},
  {"languageId": "csharp", "index": 1, "title": "C# na prática", "description": "Laços, métodos e listas", "lessons": [{"id": "cs_pratica_0", "title": "Percorrendo uma coleção"}, {"id": "cs_pratica_1", "title": "Contando de 1 a 3"}, {"id": "cs_pratica_2", "title": "Método que devolve"}, {"id": "cs_pratica_3", "title": "Lista de verdade"}, {"id": "cs_pratica_4", "title": "Pode não ter valor"}, {"id": "cs_pratica_5", "title": "Para onde ir agora"}]},
  {"languageId": "go", "index": 0, "title": "Go: primeiros passos", "description": "Simples de propósito, rápido de rodar", "lessons": [{"id": "go_basic_0", "title": "A linguagem que cortou o excesso"}, {"id": "go_basic_1", "title": "Escrevendo na tela"}, {"id": "go_basic_2", "title": "Variável em uma linha"}, {"id": "go_basic_3", "title": "O tipo vem depois"}, {"id": "go_basic_4", "title": "if sem parênteses"}, {"id": "go_basic_5", "title": "Erro é valor"}]},
  {"languageId": "go", "index": 1, "title": "Go na prática", "description": "Laços, funções e slices", "lessons": [{"id": "go_pratica_0", "title": "Um laço só"}, {"id": "go_pratica_1", "title": "Percorrendo uma lista"}, {"id": "go_pratica_2", "title": "Função que devolve"}, {"id": "go_pratica_3", "title": "Slice que cresce"}, {"id": "go_pratica_4", "title": "Rodando em paralelo"}, {"id": "go_pratica_5", "title": "Para onde ir agora"}]},
  {"languageId": "php", "index": 0, "title": "PHP: primeiros passos", "description": "A linguagem que move boa parte da web", "lessons": [{"id": "php_basic_0", "title": "PHP ainda está em todo lugar"}, {"id": "php_basic_1", "title": "Escrevendo na tela"}, {"id": "php_basic_2", "title": "Toda variável tem cifrão"}, {"id": "php_basic_3", "title": "Juntando textos"}, {"id": "php_basic_4", "title": "Decidindo com if"}, {"id": "php_basic_5", "title": "Array com nome"}]},
  {"languageId": "php", "index": 1, "title": "PHP na prática", "description": "Laços, funções e formulários", "lessons": [{"id": "php_pratica_0", "title": "Percorrendo um array"}, {"id": "php_pratica_1", "title": "Função que devolve"}, {"id": "php_pratica_2", "title": "Dado que veio do formulário"}, {"id": "php_pratica_3", "title": "Nunca confie no que chega"}, {"id": "php_pratica_4", "title": "Contando de 1 a 3"}, {"id": "php_pratica_5", "title": "Para onde ir agora"}]},
  {"languageId": "ruby", "index": 0, "title": "Ruby: primeiros passos", "description": "Código que lê quase como uma frase", "lessons": [{"id": "rb_basic_0", "title": "Ruby foi feita para a pessoa"}, {"id": "rb_basic_1", "title": "Escrevendo na tela"}, {"id": "rb_basic_2", "title": "Sem tipo, sem ponto e vírgula"}, {"id": "rb_basic_3", "title": "Texto com valor dentro"}, {"id": "rb_basic_4", "title": "if que fecha com end"}, {"id": "rb_basic_5", "title": "Tudo é objeto"}]},
  {"languageId": "ruby", "index": 1, "title": "Ruby na prática", "description": "Blocos, métodos e coleções", "lessons": [{"id": "rb_pratica_0", "title": "Percorrendo com bloco"}, {"id": "rb_pratica_1", "title": "Método que devolve"}, {"id": "rb_pratica_2", "title": "Transformando uma lista"}, {"id": "rb_pratica_3", "title": "Filtrando"}, {"id": "rb_pratica_4", "title": "Símbolo ou texto"}, {"id": "rb_pratica_5", "title": "Para onde ir agora"}]},
  {"languageId": "cpp", "index": 0, "title": "C++: primeiros passos", "description": "Onde cada microssegundo conta", "lessons": [{"id": "cpp_basic_0", "title": "Por que C++ ainda domina"}, {"id": "cpp_basic_1", "title": "Escrevendo na tela"}, {"id": "cpp_basic_2", "title": "Trazendo a biblioteca"}, {"id": "cpp_basic_3", "title": "Todo valor tem tipo"}, {"id": "cpp_basic_4", "title": "Decidindo com if"}, {"id": "cpp_basic_5", "title": "O erro que só C++ tem"}]},
  {"languageId": "cpp", "index": 1, "title": "C++ na prática", "description": "Laços, funções e vetores", "lessons": [{"id": "cpp_pratica_0", "title": "Contando de 1 a 3"}, {"id": "cpp_pratica_1", "title": "Lista que cresce"}, {"id": "cpp_pratica_2", "title": "Função que devolve"}, {"id": "cpp_pratica_3", "title": "Passando sem copiar"}, {"id": "cpp_pratica_4", "title": "Quem apaga a memória"}, {"id": "cpp_pratica_5", "title": "Para onde ir agora"}]},
  {"languageId": "c", "index": 0, "title": "C: primeiros passos", "description": "A base sobre a qual quase tudo foi construído", "lessons": [{"id": "c_basic_0", "title": "C é a linguagem embaixo das outras"}, {"id": "c_basic_1", "title": "Escrevendo na tela"}, {"id": "c_basic_2", "title": "Mostrando um número"}, {"id": "c_basic_3", "title": "Texto é um vetor"}, {"id": "c_basic_4", "title": "Decidindo com if"}, {"id": "c_basic_5", "title": "O endereço de uma variável"}]},
  {"languageId": "c", "index": 1, "title": "C na prática", "description": "Laços, funções e ponteiros", "lessons": [{"id": "c_pratica_0", "title": "Contando de 1 a 3"}, {"id": "c_pratica_1", "title": "Função que devolve"}, {"id": "c_pratica_2", "title": "Lendo pelo ponteiro"}, {"id": "c_pratica_3", "title": "Pedindo memória"}, {"id": "c_pratica_4", "title": "Agrupando campos"}, {"id": "c_pratica_5", "title": "Para onde ir agora"}]},
  {"languageId": "rust", "index": 0, "title": "Rust: primeiros passos", "description": "Velocidade de C sem os acidentes de memória", "lessons": [{"id": "rust_basic_0", "title": "O compilador é seu revisor"}, {"id": "rust_basic_1", "title": "A exclamação da macro"}, {"id": "rust_basic_2", "title": "Imutável por padrão"}, {"id": "rust_basic_3", "title": "Quem é o dono"}, {"id": "rust_basic_4", "title": "Emprestando em vez de dar"}, {"id": "rust_basic_5", "title": "Pode dar errado"}]},
  {"languageId": "rust", "index": 1, "title": "Rust na prática", "description": "Laços, funções e match", "lessons": [{"id": "rust_pratica_0", "title": "Contando de 1 a 3"}, {"id": "rust_pratica_1", "title": "Função que devolve"}, {"id": "rust_pratica_2", "title": "Tratando cada caso"}, {"id": "rust_pratica_3", "title": "Pode não ter valor"}, {"id": "rust_pratica_4", "title": "Vetor que cresce"}, {"id": "rust_pratica_5", "title": "Para onde ir agora"}]},
  {"languageId": "kotlin", "index": 0, "title": "Kotlin: primeiros passos", "description": "A linguagem oficial do Android", "lessons": [{"id": "kt_basic_0", "title": "Kotlin resolveu o incômodo do Java"}, {"id": "kt_basic_1", "title": "Escrevendo na tela"}, {"id": "kt_basic_2", "title": "val ou var"}, {"id": "kt_basic_3", "title": "Pode ser nulo"}, {"id": "kt_basic_4", "title": "Texto com valor dentro"}, {"id": "kt_basic_5", "title": "if que devolve valor"}]},
  {"languageId": "kotlin", "index": 1, "title": "Kotlin na prática", "description": "Laços, funções e listas", "lessons": [{"id": "kt_pratica_0", "title": "Percorrendo uma lista"}, {"id": "kt_pratica_1", "title": "Contando de 1 a 3"}, {"id": "kt_pratica_2", "title": "Função que devolve"}, {"id": "kt_pratica_3", "title": "Classe em uma linha"}, {"id": "kt_pratica_4", "title": "Lidando com o nulo"}, {"id": "kt_pratica_5", "title": "Para onde ir agora"}]},
  {"languageId": "swift", "index": 0, "title": "Swift: primeiros passos", "description": "A linguagem do iPhone, iPad e Apple Watch", "lessons": [{"id": "swift_basic_0", "title": "Swift é o presente da Apple"}, {"id": "swift_basic_1", "title": "let ou var"}, {"id": "swift_basic_2", "title": "Tipo depois dos dois pontos"}, {"id": "swift_basic_3", "title": "Texto com valor dentro"}, {"id": "swift_basic_4", "title": "Opcional é explícito"}, {"id": "swift_basic_5", "title": "Abrindo o opcional com segurança"}]},
  {"languageId": "swift", "index": 1, "title": "Swift na prática", "description": "Laços, funções e coleções", "lessons": [{"id": "swift_pratica_0", "title": "Percorrendo um array"}, {"id": "swift_pratica_1", "title": "Contando de 1 a 3"}, {"id": "swift_pratica_2", "title": "Função que devolve"}, {"id": "swift_pratica_3", "title": "Struct ou class"}, {"id": "swift_pratica_4", "title": "Dicionário"}, {"id": "swift_pratica_5", "title": "Para onde ir agora"}]},
  {"languageId": "dart", "index": 0, "title": "Dart: primeiros passos", "description": "A linguagem por trás deste app", "lessons": [{"id": "dart_basic_0", "title": "O Buggo foi escrito em Dart"}, {"id": "dart_basic_1", "title": "Escrevendo na tela"}, {"id": "dart_basic_2", "title": "Valor que não muda"}, {"id": "dart_basic_3", "title": "final ou const"}, {"id": "dart_basic_4", "title": "Texto com valor dentro"}, {"id": "dart_basic_5", "title": "Nulo é opcional"}]},
  {"languageId": "dart", "index": 1, "title": "Dart na prática", "description": "Laços, funções e listas", "lessons": [{"id": "dart_pratica_0", "title": "Percorrendo uma lista"}, {"id": "dart_pratica_1", "title": "Função de uma linha"}, {"id": "dart_pratica_2", "title": "Transformando uma lista"}, {"id": "dart_pratica_3", "title": "Parâmetro com nome"}, {"id": "dart_pratica_4", "title": "Esperando o que demora"}, {"id": "dart_pratica_5", "title": "Para onde ir agora"}]},
  {"languageId": "queries", "index": 0, "title": "Consultas: primeiros passos", "description": "Perguntar ao banco e receber a resposta", "lessons": [{"id": "sql_basic_0", "title": "SQL é uma pergunta bem feita"}, {"id": "sql_basic_1", "title": "Escolhendo colunas"}, {"id": "sql_basic_2", "title": "Filtrando linhas"}, {"id": "sql_basic_3", "title": "Ordenando o resultado"}, {"id": "sql_basic_4", "title": "Só os primeiros"}, {"id": "sql_basic_5", "title": "O vazio tem nome"}]},
  {"languageId": "queries", "index": 1, "title": "Consultas na prática", "description": "Contar, agrupar e juntar tabelas", "lessons": [{"id": "sql_pratica_0", "title": "Contando linhas"}, {"id": "sql_pratica_1", "title": "Somando por grupo"}, {"id": "sql_pratica_2", "title": "WHERE ou HAVING"}, {"id": "sql_pratica_3", "title": "Juntando duas tabelas"}, {"id": "sql_pratica_4", "title": "Quando faltar o par"}, {"id": "sql_pratica_5", "title": "Para onde ir agora"}]},
];
